### ISSUE TITLE
Issues connecting to sample app following deployment

### ISSUE THREAD

**Issue by cjwells-ora** [oracle-devrel/terraform-oci-arch-tomcat-autonomous#13]
Getting the following errors during the deployment, resulting in an error 502 when trying to access the application. In job details, it has a status of: "SUCCEEDED":

null_resource.tomcat_server_config_with_bastion[1] (remote-exec): Errors during downloading metadata for repository 'ol8_ksplice':
null_resource.tomcat_server_config_with_bastion[1] (remote-exec): Error: Failed to download metadata for repo 'ol8_ksplice': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
null_resource.tomcat_server_config_with_bastion[0] (remote-exec): Errors during downloading metadata for repository 'ol8_ksplice':
null_resource.tomcat_server_config_with_bastion[0] (remote-exec): Error: Failed to download metadata for repo 'ol8_ksplice': Yum repo downloading error: Downloading error(s): repodata/c777785048c9ca01d1b61db72d4b0ddf9987ca1f-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/c8353de4debe349b443b0e8b813444729f3c4b93-filelists.xml.gz - Cannot download, all mirrors were already tried without success
null_resource.tomcat_server_config_with_bastion[1] (remote-exec): Errors during downloading metadata for repository 'ol8_ksplice':
null_resource.tomcat_server_config_with_bastion[1] (remote-exec): Error: Failed to download metadata for repo 'ol8_ksplice': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
null_resource.tomcat_server_config_with_bastion[1] (remote-exec): Errors during downloading metadata for repository 'ol8_ksplice':
null_resource.tomcat_server_config_with_bastion[1] (remote-exec): Error: Failed to download metadata for repo 'ol8_ksplice': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
null_resource.tomcat_server_config_with_bastion[0] (remote-exec): Errors during downloading metadata for repository 'ol8_ksplice':
null_resource.tomcat_server_config_with_bastion[0] (remote-exec): Error: Failed to download metadata for repo 'ol8_ksplice': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
null_resource.tomcat_server_config_with_bastion[0] (remote-exec): Errors during downloading metadata for repository 'ol8_MySQL80':
null_resource.tomcat_server_config_with_bastion[0] (remote-exec): Error: Failed to download metadata for repo 'ol8_MySQL80': Yum repo downloading error: Downloading error(s): repodata/e1bf72614b2807b57db2730f6c0d460702e49482-primary.xml.gz - Cannot download, all mirrors were already tried without success
null_resource.tomcat_server_config_with_bastion[1] (remote-exec): Job for tomcat.service failed because the control process exited with error code.
null_resource.tomcat_server_config_with_bastion[0] (remote-exec): Job for tomcat.service failed because the control process exited with error code.

**Comment by lfeldman** [comment]
Looks like temporary YUM repositories were unavailable. I was able to install all elements from the bootstrap script by hand:
![image](https://user-images.githubusercontent.com/19390609/168296561-7eb724ad-794f-4e76-ad51-72c94b6d857f.png)
![image](https://user-images.githubusercontent.com/19390609/168296609-309e6124-8e94-4be4-8552-21f0f94e19c2.png)
![image](https://user-images.githubusercontent.com/19390609/168296663-b4247e0f-9c02-4305-aa82-cda5266985c3.png)

I recommend destroying the stack in ORM and redeploying it with apply command.
